#!/usr/bin/env php
<?php

$loader = require __DIR__ . '/autoload.php';

use MVC\Console\Application;
use MVC\Console\Input\ArgvInput;

$input = new ArgvInput();
$debug = (!$input->hasParameterOption(array('--no-debug', ''))) ? true: false;

/*
$settings = array(
    'app_path' => './app'
    'views_path' => './Views',
    'models_path' => './Models',
    'controllers_path' => './Controllers'
);
$command = new MVC\Command\Command(__DIR__, $settings);
*/

$mvc = new AppMVC(array(
    'debug' => $debug
));
$application = new Application($mvc);
$application->run($input);